version: '3'

services:
  nodejs-ctorres:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs-ctorres
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "10450:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - ctorres_app-network
    command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js


  db-ctorres:
    image: mongo:4.1.8-xenial
    container_name: db-ctorres
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:     
      - ctorres_dbdata:/data/db
    networks:
      - ctorres_app-network  


networks:
  ctorres_app-network:
    driver: bridge


volumes:
  ctorres_dbdata:
  ctorres_node_modules: 